METHOD: DMPHN_1_2_4
EXPNAME: exp1

PRETRAINED:
  USE_PRETRAINED: True
  # PRETRAINED_FOLDER: /home/fedynyak/NTIRE2021/models/ind_v3_multinet
  # PRETRAINED_FOLDER: /home/fedynyak/NTIRE2021/egs/Nonhomogeneous_Image_Dehazing/exp1/models/
  PRETRAINED_FOLDER: /home/fedynyak/NTIRE2021/models/ind_v4_pretrained_combined

TRAINSETS:
  
  DATASETS:
    DATASET1:
      ALREADY_CROPED: True
      ORIG_DATA_FREE: /home/fedynyak/NTIRE2021/data/NTIRE2021-HAZE/GT
      ORIG_DATA_HAZY: /home/fedynyak/NTIRE2021/data/NTIRE2021-HAZE/hazy
      CROPED_DATA_FREE: exp1/data/NTIRE2021-HAZE/GT
      CROPED_DATA_HAZY: exp1/data/NTIRE2021-HAZE/hazy
      CROP_TIMES: 10
      BATCH_SIZE : 80
      NUM_WORKERS: 10

    DATASET2:
      ALREADY_CROPED: True
      ORIG_DATA_FREE: /home/fedynyak/NTIRE2021/data/DENSE-HAZE/GT
      ORIG_DATA_HAZY: /home/fedynyak/NTIRE2021/data/DENSE-HAZE/hazy
      CROPED_DATA_FREE: exp1/data/DENSE-HAZE/GT
      CROPED_DATA_HAZY: exp1/data/DENSE-HAZE/hazy
      CROP_TIMES: 10
      BATCH_SIZE : 80
      NUM_WORKERS: 10
    
    DATASET3:
      ALREADY_CROPED: True
      ORIG_DATA_FREE: /home/fedynyak/NTIRE2021/data/I-HAZE-RESCALED/GT
      ORIG_DATA_HAZY: /home/fedynyak/NTIRE2021/data/I-HAZE-RESCALED/hazy
      CROPED_DATA_FREE: exp1/data/I-HAZE/GT
      CROPED_DATA_HAZY: exp1/data/I-HAZE/hazy
      CROP_TIMES: 10
      BATCH_SIZE : 80
      NUM_WORKERS: 10

    DATASET4:
      ALREADY_CROPED: True
      ORIG_DATA_FREE: /home/fedynyak/NTIRE2021/data/O-HAZE-RESCALED/GT
      ORIG_DATA_HAZY: /home/fedynyak/NTIRE2021/data/O-HAZE-RESCALED/hazy
      CROPED_DATA_FREE: exp1/data/O-HAZE/GT
      CROPED_DATA_HAZY: exp1/data/O-HAZE/hazy
      CROP_TIMES: 10
      BATCH_SIZE : 80
      NUM_WORKERS: 10

    DATASET5:
      ALREADY_CROPED: True
      ORIG_DATA_FREE: /home/fedynyak/NTIRE2021/data/NH-HAZE/GT
      ORIG_DATA_HAZY: /home/fedynyak/NTIRE2021/data/NH-HAZE/hazy
      CROPED_DATA_FREE: exp1/data/NH-HAZE/GT
      CROPED_DATA_HAZY: exp1/data/NH-HAZE/hazy
      CROP_TIMES: 10
      BATCH_SIZE : 80
      NUM_WORKERS: 10

TRAINING:
  GPU: 0
  LEARNING_RATE: 0.0001
  EPOCHS: 300
  START_EPOCH: 1
  LOGGING_FREQ: 25


TESTING:
  DATA_HAZY: /home/fedynyak/NTIRE2021/data/valid_set
  DEHAZED_PATH: exp1/dehazed/
  EPOCH_FREQ: 1


VALIDATION:
  EPOCH_FREQ: 1
  DATASETS:
    NTIRE2020:
      DATA_FREE: /home/fedynyak/NTIRE2021/data/NH-HAZE/GT
      DATA_HAZY: /home/fedynyak/NTIRE2021/data/NH-HAZE/hazy
    NTIRE2021:
      DATA_FREE: /home/fedynyak/NTIRE2021/data/NTIRE2021-HAZE/GT
      DATA_HAZY: /home/fedynyak/NTIRE2021/data/NTIRE2021-HAZE/hazy
    DENSE-HAZE:
      DATA_FREE: /home/fedynyak/NTIRE2021/data/DENSE-HAZE/GT
      DATA_HAZY: /home/fedynyak/NTIRE2021/data/DENSE-HAZE/hazy
    O-HAZE:
      DATA_FREE: /home/fedynyak/NTIRE2021/data/O-HAZE-RESCALED/GT
      DATA_HAZY: /home/fedynyak/NTIRE2021/data/O-HAZE-RESCALED/hazy
    I-HAZE:
      DATA_FREE: /home/fedynyak/NTIRE2021/data/I-HAZE-RESCALED/GT
      DATA_HAZY: /home/fedynyak/NTIRE2021/data/I-HAZE-RESCALED/hazy


MODEL_SAVING:
  SAVING_FOLDER: exp1/models
