EXP_PATH: &PATH experiments/exp_test
MODEL: models/MID_SMP.pkl

TESTING:
  # NTIRE2020:
  #   INPUT_FOLDER: data/NH-HAZE/hazy
  #   OUTPUT_FOLDER: !join [*PATH, NH-HAZE]
  NTIRE2021:
    INPUT_FOLDER: data/NTIRE2021-HAZE/hazy
    GT: data/NTIRE2021-HAZE/GT
    OUTPUT_FOLDER: !join [*PATH, NTIRE2021-HAZE]
#   DENSE-HAZE:
#     INPUT_FOLDER: data/DENSE-HAZE/hazy
#     OUTPUT_FOLDER: !join [*PATH, DENSE-HAZE]
#   O-HAZE:
#     INPUT_FOLDER: data/O-HAZE-RESCALED/hazy
#     OUTPUT_FOLDER: !join [*PATH, O-HAZE-RESCALED]
#   I-HAZE:
#     INPUT_FOLDER: data/I-HAZE-RESCALED/hazy
#     OUTPUT_FOLDER: !join [*PATH, I-HAZE-RESCALED]
  # NTIRE2021_VALIDSET:
  #   INPUT_FOLDER: data/valid_set
  #   OUTPUT_FOLDER: !join [*PATH, valid_set]
  #   GT: data/valid_set


VALIDATION:
# NTIRE2020:
  #   INPUT_FOLDER: data/NH-HAZE/hazy
  #   OUTPUT_FOLDER: !join [*PATH, NH-HAZE]
  # NTIRE2021:
  #   INPUT_FOLDER: data/NTIRE2021-HAZE/hazy
  #   GT: data/NTIRE2021-HAZE/GT
  #   OUTPUT_FOLDER: !join [*PATH, valid_set]
  #   OUTPUT_FOLDER: !join [*PATH, NTIRE2021-HAZE]
#   DENSE-HAZE:
#     INPUT_FOLDER: data/DENSE-HAZE/hazy
#     OUTPUT_FOLDER: !join [*PATH, DENSE-HAZE]
#   O-HAZE:
#     INPUT_FOLDER: data/O-HAZE-RESCALED/hazy
#     OUTPUT_FOLDER: !join [*PATH, O-HAZE-RESCALED]
#   I-HAZE:
#     INPUT_FOLDER: data/I-HAZE-RESCALED/hazy
    # OUTPUT_FOLDER: !join [*PATH, I-HAZE-RESCALED]
  NTIRE2021_VALIDSET:
    INPUT_FOLDER: data/valid_set
    OUTPUT_FOLDER: !join [*PATH, valid_set]
