EXP_PATH: &PATH exp/train

MODEL:

	ARCHITECTURE: ColorSegmentator
	LOSS:
		ARCH: LaplacianLoss
		PARAMS:

	USE_PRETRAINED: False
	PRETRAINED_MODEL:

	SAVING_FOLDER: !join [*PATH, checkpoints]
	NAME: pussy

TRAINING:

	LOGGING_FREQ: 25
	TEST_FREQ: 1
	VALID_FREQ: 1

	USE_PARALLEL: True
	USE_TENSORBOARD: True
	USE_SCHEDULER: True

	SCHEDULER:
		STEP: 25
		GAMMA: 0.5

	LEARNING_RATE: 0.0001
	EPOCHS: 3000

TRAINING_DATA:

	BATCH_SIZE: 32
	NUM_WORKERS: 10
	SHUFFLE: True

	DATASETS:
		NTIRE2021:
			HAZY:
				DATA_FREE: prepared/NTIRE2021_5X5_HAZE/GT
				DATA_HAZY: prepared/NTIRE2021_5X5_HAZE/hazy
			MAX:
				DATA_FREE: prepared/NTIRE2021_5X5_MAX/
				DATA_HAZY: prepared/NTIRE2021_5X5_MAX/
			MID:
				DATA_FREE: prepared/NTIRE2021_5X5_MID/
				DATA_HAZY: prepared/NTIRE2021_5X5_MID/
			MIN:
				DATA_FREE: prepared/NTIRE2021_5X5_MIN/
				DATA_HAZY: prepared/NTIRE2021_5X5_MIN/
		# NTIRE2020:
			# HAZY:
				# DATA_FREE:
				# DATA_HAZY:
		# DENSE:
			# HAZY:
				# DATA_FREE:
				# DATA_HAZY:
		# IHAZE:
			# HAZY:
				# DATA_FREE:
				# DATA_HAZY:
		# OHAZE:
			# HAZY:
				# DATA_FREE:
				# DATA_HAZY:

TESTING_DATA:

	BATCH_SIZE: 1
	NUM_WORKERS: 10
	SHUFFLE: False

	DATASETS:
		VALID_2021:
			HAZY:
				DATA_FREE: data/valid_set
				DATA_HAZY: data/valid_set

VALIDATION_DATA:

	BATCH_SIZE: 1
	NUM_WORKERS: 10
	SHUFFLE: False

	DATASETS:
		NTIRE2020:
			HAZY:
				DATA_FREE: data/NH-HAZE/GT
				DATA_HAZY: data/NH-HAZE/hazy
		NTIRE2021:
			HAZY:
				DATA_FREE: data/NTIRE2021-HAZE/GT
				DATA_HAZY: data/NTIRE2021-HAZE/hazy
		DENSE-HAZE:
			HAZY:
				DATA_FREE: data/DENSE-HAZE/GT
				DATA_HAZY: data/DENSE-HAZE/hazy
		O-HAZE:
			HAZY:
				DATA_FREE: data/O-HAZE-RESCALED/GT
				DATA_HAZY: data/O-HAZE-RESCALED/hazy
		I-HAZE:
			HAZY:
				DATA_FREE: data/I-HAZE-RESCALED/GT
				DATA_HAZY: data/I-HAZE-RESCALED/hazy
