EXP_PATH: &PATH experiments/exp_dense

PRETRAINED:
  USE_PRETRAINED: False
  PRETRAINED_MODEL: models/hybrid_v1.pkl


TRAINSETS:
  
  DATASETS:
    # DATASET1:
    #   ALREADY_CROPED: False
    #   ORIG_DATA_FREE: data/NTIRE2021-HAZE/GT
    #   ORIG_DATA_HAZY: data/NTIRE2021-HAZE/hazy
    #   CROPED_DATA_FREE: !join [*PATH, NTIRE2021-HAZE/GT]
    #   CROPED_DATA_HAZY: !join [*PATH, NTIRE2021-HAZE/hazy]
    #   CROP_TIMES: 10
    #   BATCH_SIZE : 4
    #   NUM_WORKERS: 10

    DATASET2:
      ALREADY_CROPED: True
      ORIG_DATA_FREE: data/DENSE-HAZE/GT
      ORIG_DATA_HAZY: data/DENSE-HAZE/hazy
      CROPED_DATA_FREE: !join [*PATH, DENSE-HAZE/GT]
      CROPED_DATA_HAZY: !join [*PATH, DENSE-HAZE/hazy]
      CROP_TIMES: 10
      BATCH_SIZE : 64
      NUM_WORKERS: 10
    
    # DATASET3:
    #   ALREADY_CROPED: True
    #   ORIG_DATA_FREE: data/I-HAZE-RESCALED/GT
    #   ORIG_DATA_HAZY: data/I-HAZE-RESCALED/hazy
    #   CROPED_DATA_FREE: !join [*PATH, I-HAZE/GT]
    #   CROPED_DATA_HAZY: !join [*PATH, I-HAZE/hazy]
    #   CROP_TIMES: 10
    #   BATCH_SIZE : 2
    #   NUM_WORKERS: 10

    # DATASET4:
    #   ALREADY_CROPED: True
    #   ORIG_DATA_FREE: data/O-HAZE-RESCALED/GT
    #   ORIG_DATA_HAZY: data/O-HAZE-RESCALED/hazy
    #   CROPED_DATA_FREE: !join [*PATH, O-HAZE/GT]
    #   CROPED_DATA_HAZY: !join [*PATH, O-HAZE/hazy]
    #   CROP_TIMES: 10
    #   BATCH_SIZE : 40
    #   NUM_WORKERS: 10

    # DATASET5:
    #   ALREADY_CROPED: True
    #   ORIG_DATA_FREE: data/NH-HAZE/GT
    #   ORIG_DATA_HAZY: data/NH-HAZE/hazy
    #   CROPED_DATA_FREE: !join [*PATH, NH-HAZE/GT]
    #   CROPED_DATA_HAZY: !join [*PATH, NH-HAZE/hazy]
    #   CROP_TIMES: 10
    #   BATCH_SIZE : 24
    #   NUM_WORKERS: 10

TRAINING:
  GPU: 0
  LEARNING_RATE: 0.0001
  EPOCHS: 300
  START_EPOCH: 1
  LOGGING_FREQ: 25


TESTING:
  DATA_HAZY: data/valid_set
  DEHAZED_PATH: !join [*PATH, dehazed]
  EPOCH_FREQ: 3


VALIDATION:
  EPOCH_FREQ: 6
  DATASETS:
    NTIRE2020:
      DATA_FREE: data/NH-HAZE/GT
      DATA_HAZY: data/NH-HAZE/hazy
    NTIRE2021:
      DATA_FREE: data/NTIRE2021-HAZE/GT
      DATA_HAZY: data/NTIRE2021-HAZE/hazy
    DENSE-HAZE:
      DATA_FREE: data/DENSE-HAZE/GT
      DATA_HAZY: data/DENSE-HAZE/hazy
    # O-HAZE:
    #   DATA_FREE: data/O-HAZE-RESCALED/GT
    #   DATA_HAZY: data/O-HAZE-RESCALED/hazy
    # I-HAZE:
    #   DATA_FREE: data/I-HAZE-RESCALED/GT
    #   DATA_HAZY: data/I-HAZE-RESCALED/hazy


MODEL_SAVING:
  SAVING_FOLDER: !join [*PATH, models]
  SAVING_NAME: dense_dehazer_v1.pkl
