EXP_PATH: &PATH experiments/exp_test
MODEL: models/hybrid_v1.pkl

TESTING:
  NTIRE2020:
    INPUT_FOLDER: data/NH-HAZE/hazy
    OUTPUT_FOLDER: !join [*PATH, NH-HAZE]
  NTIRE2021:
    INPUT_FOLDER: data/NTIRE2021-HAZE/hazy
    OUTPUT_FOLDER: !join [*PATH, NTIRE2021-HAZE]
  DENSE-HAZE:
    INPUT_FOLDER: data/DENSE-HAZE/hazy
    OUTPUT_FOLDER: !join [*PATH, DENSE-HAZE]
  O-HAZE:
    INPUT_FOLDER: data/O-HAZE-RESCALED/hazy
    OUTPUT_FOLDER: !join [*PATH, O-HAZE-RESCALED]
  I-HAZE:
    INPUT_FOLDER: data/I-HAZE-RESCALED/hazy
    OUTPUT_FOLDER: !join [*PATH, I-HAZE-RESCALED]
  NTIRE2021_VALIDSET:
    INPUT_FOLDER: data/valid_set
    OUTPUT_FOLDER: !join [*PATH, valid_set]


VALIDATION:
  NTIRE2020:
    DATA_FREE: data/NH-HAZE/GT
    DATA_HAZY: data/NH-HAZE/hazy
  NTIRE2021:
    DATA_FREE: data/NTIRE2021-HAZE/GT
    DATA_HAZY: data/NTIRE2021-HAZE/hazy
  DENSE-HAZE:
    DATA_FREE: data/DENSE-HAZE/GT
    DATA_HAZY: data/DENSE-HAZE/hazy
  O-HAZE:
    DATA_FREE: data/O-HAZE-RESCALED/GT
    DATA_HAZY: data/O-HAZE-RESCALED/hazy
  I-HAZE:
    DATA_FREE: data/I-HAZE-RESCALED/GT
    DATA_HAZY: data/I-HAZE-RESCALED/hazy
